### ISSUE TITLE
Compatibility with GPUView

### ISSUE THREAD

**Issue by MikeGameDev** [microsoft/tracelogging#18]
I'm noticing that GPUView has some trouble displaying events logged using the TraceLogging API. 

It seems that the first event name to be logged using the TraceLoggingWrite is the only one that will show up in GPUView. 

i.e.

```
void main()
{
...
		TraceLoggingWrite(g_hMyProvider, "EventA");    // <- This event will appear in GPUView
		TraceLoggingWrite(g_hMyProvider, "EventB");    // <- This event will not appear in GPUView
                TraceLoggingWrite(g_hMyProvider, "EventA");    // <- This event will appear in GPUView
...
}
```

I've confirmed that the traces are good as TraceView is able to display all of the events as expected. 

Is there anything I can do to make TraceLogging play nicely with GPUView? Or would it make more sense for me to switch to using a manifest based ETW solution?

**Comment by nickbopp** [comment]
This repository is for making the TraceLogging API work on Linux using LTTNG rather than the ETW layer that exists on Windows.  

If your TraceLogging events are visible in other ETL-parsing tools, then you would need support from the owner of the GPUView tool which is not parsing the events correctly.  It's possible that tool simply doesn't parse TraceLogging events out of the ETL correctly.
