### ISSUE TITLE
Performance comparison with Manifest-based provider

### ISSUE THREAD

**Issue by velbharathi** [microsoft/tracelogging#59]
Hi Team,
How does this Trace Logging helper for ETW compare(Performance and overhead) with manifest-based provider?

Thanks

**Comment by idigdoug** [comment]
Detailed data would depend on your own scenario, so you would have to do your own comparison. However, general experience is that the main difference between manifest and TraceLogging is that the logged events take more space in the trace buffers and in the trace file.

If you are logging very high-volume events where the log file size is a major issue then switching to TraceLogging might be a bad idea. Otherwise, the performance issues don't seem to be significant.
